---
- name: Deploy application
  hosts: app
  tasks:
    - name: APT Install
      become : true
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Fetch the latest version of application code
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/ubuntu/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

  handlers:
  - name: reload puma
    become : true
    systemd: name=puma state=restarted
